
// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Modules.Events.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class UpdateEventsDbContextChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Events_Categories_CategoryId",
                schema: "Events",
                table: "Events");

            migrationBuilder.CreateTable(
                name: "TicketTypes",
                schema: "Events",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    EventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Price = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Currency = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Quantity = table.Column<decimal>(type: "decimal(18,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TicketTypes", x => x.Id);
                });

            migrationBuilder.AddForeignKey(
                name: "FK_Events_Categories_CategoryId",
                schema: "Events",
                table: "Events",
                column: "CategoryId",
                principalSchema: "Events",
                principalTable: "Categories",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Events_Categories_CategoryId",
                schema: "Events",
                table: "Events");

            migrationBuilder.DropTable(
                name: "TicketTypes",
                schema: "Events");

            migrationBuilder.AddForeignKey(
                name: "FK_Events_Categories_CategoryId",
                schema: "Events",
                table: "Events",
                column: "CategoryId",
                principalSchema: "Events",
                principalTable: "Categories",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
